name: Trigger artifact build

on:
  push:
    branches: [ 2.x-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger artifact to build.
        run: |
          curl -X POST https://api.github.com/repos/JudicialCouncilOfCalifornia/courtyard-artifact/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.CourtyardArtifactToken }} \
          --data '{"event_type": "trigger-build-dev", "client_payload": {}}'
